import { H2 } from "@/components/h2";
import { ProductCard } from "@/components/product-card";
import { Account } from "@/components/account";
import { ThemeToggle } from "@/components/theme-toggle";
import { Button } from "@/components/ui/button";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import { Products } from "@/components/products";

export default function Home() {
  const categories = api.category.getCategories.useQuery();

  // TODO: return a loading state
  if (categories.data == undefined) {
    return null;
  }

  return (
    <>
      <Head>
        <title>Catalog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-8 px-16">
        <header>
          <div className="flex gap-6">
            <H2 className="my-4">CH9 Specialty Coffee</H2>
            <ThemeToggle />
            <Account />
          </div>
          <p className="opacity-60">Here's a list of all things for sale!</p>
        </header>
        <div className="my-4">
          <Products categories={categories.data}></Products>
        </div>
      </main>
    </>
  );
}
